ALTER SEQUENCE "Train_numero_seq" RESTART WITH 1;
ALTER SEQUENCE "Station_id_seq" RESTART WITH 1;
ALTER SEQUENCE "Trajet_id_seq" RESTART WITH 1;
ALTER SEQUENCE "Troncon_id_seq" RESTART WITH 1;
ALTER SEQUENCE "Reservation_id_seq" RESTART WITH 1;
ALTER SEQUENCE "Place_id_seq" RESTART WITH 1;
